# Generated by Django 6.0.1 on 2026-05-22 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_offers/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storeapp.category')),
            ],
        ),
    ]
